#!/usr/bin/env python3
"""
Still — deterministic day-plan rebuild (GitHub Actions, Brazil-proof).

Pure rails, no AI. Every 30 minutes during the day it:
  1. Reads the Joint Plans + Junyan calendars (secret ICS URLs) for TODAY.
  2. Treats every calendar event as a FIXED block, drops Still's own
     "🌊 Focus — …" events, and fills the remaining daytime gaps with
     focus blocks separated by short rests.
  3. Splices the result into still/index.html between the STILL:PLAN markers
     and stamps a cache-busting version so phones fetch the fresh plan.

Only future gaps are replanned: blocks that already started are left exactly as
the previous run wrote them, so the page never rewrites the block you're in.

Times are emitted with the calendars' own America/Toronto offsets, unchanged.
Junyan's phone renders them in device-local time (São Paulo), which is what makes
a class stored 18:30-04:00 display correctly as 19:30. Never shift these.

The workflow commits still/index.html only when it changed. Junyan's in-app edits
live in his phone's localStorage and are layered over this plan at render time, so
a rebuild never destroys them.

Fail policy: a calendar-source failure aborts nonzero and writes nothing.
"""

import os
import re
import sys
import json
from datetime import datetime, timedelta
from zoneinfo import ZoneInfo

import requests
import icalendar
import recurring_ical_events

TZ = ZoneInfo("America/Toronto")
HERE = os.path.dirname(os.path.abspath(__file__))
STILL = os.path.join(HERE, "..", "still", "index.html")

# Calendars that feed Still. Staff Scheduling is deliberately excluded —
# Junyan removed it from this system on 2026-07-30.
CALS = [
    {"env": "ICS_URL_JOINT",  "label": "Joint Plans"},
    {"env": "ICS_URL_JUNYAN", "label": "Junyan"},
]

FOCUS_MIN = 50          # length of a generated focus block
REST_MIN = 10           # breather between consecutive focus blocks
MIN_GAP = 25            # ignore gaps too short to be worth a block
DAY_START = 8           # don't generate focus before 08:00 (calendar-local)
DAY_END = 21            # ...or after 21:00
MARK_START = "// STILL:PLAN:START — regenerated by scripts/still_plan.py. Hand-edits here are overwritten."
MARK_END = "// STILL:PLAN:END"


def die(msg):
    print(f"FATAL: {msg}", file=sys.stderr)
    sys.exit(1)


def fetch_events(env, url, day_start, day_end, label):
    """Return [{summary, start, end, label}] of timed events in the window."""
    try:
        r = requests.get(url, timeout=30)
        r.raise_for_status()
        cal = icalendar.Calendar.from_ical(r.content)
    except Exception as e:
        die(f"calendar '{label}' ({env}) failed to fetch/parse: {e}")

    out = []
    for e in recurring_ical_events.of(cal).between(day_start, day_end):
        summary = str(e.get("SUMMARY", "")).strip()
        if not summary:
            continue
        if str(e.get("STATUS", "")).upper() == "CANCELLED":
            continue
        if summary.lower() in ("unavailable", "busy"):
            continue
        # Still's own output — never treat it as a fixed commitment.
        if summary.startswith("🌊 Focus"):
            continue
        dt = e.get("DTSTART").dt
        de = e.get("DTEND").dt if e.get("DTEND") else None
        if not isinstance(dt, datetime) or not isinstance(de, datetime):
            continue                      # all-day (hotel stays etc.) — not a block
        out.append({"summary": summary, "start": dt.astimezone(TZ),
                    "end": de.astimezone(TZ), "label": label})
    return out


def iso(dt):
    """ISO with the calendar's own offset, e.g. 2026-07-31T18:30:00-04:00."""
    return dt.strftime("%Y-%m-%dT%H:%M:%S%z")[:-2] + ":" + dt.strftime("%z")[-2:]


def merge_fixed(events):
    """Sort, and drop events fully contained inside an earlier one."""
    events.sort(key=lambda e: (e["start"], e["end"]))
    kept = []
    for e in events:
        if any(k["start"] <= e["start"] and e["end"] <= k["end"] for k in kept):
            continue
        kept.append(e)
    return kept


def fill_gaps(fixed, now, day_start, start_n=0):
    """Generate focus/rest blocks in the gaps between fixed events.

    start_n continues the numbering past any blocks already used earlier today,
    so a rebuild never produces a second "Quiet time II"."""
    lo = max(now, day_start.replace(hour=DAY_START, minute=0))
    hi = day_start.replace(hour=DAY_END, minute=0)
    edges = [(f["start"], f["end"]) for f in fixed]

    # Candidate windows = time between the end of one fixed event and the start
    # of the next, clipped to [lo, hi].
    windows, cursor = [], lo
    for s, e in edges:
        if s > cursor:
            windows.append((cursor, min(s, hi)))
        cursor = max(cursor, e)
    if cursor < hi:
        windows.append((cursor, hi))

    blocks, n = [], start_n
    for ws, we in windows:
        ws = max(ws, lo)
        if (we - ws).total_seconds() / 60 < MIN_GAP:
            continue
        t = ws
        while (we - t).total_seconds() / 60 >= MIN_GAP:
            span = min(FOCUS_MIN, int((we - t).total_seconds() // 60))
            end = t + timedelta(minutes=span)
            n += 1
            blocks.append({"s": iso(t), "e": iso(end),
                           "t": "Quiet time", "type": "focus", "cal": "Junyan"})
            t = end + timedelta(minutes=REST_MIN)
            if (we - t).total_seconds() / 60 >= MIN_GAP:
                blocks.append({"s": iso(end), "e": iso(t),
                               "t": "Rest", "type": "break", "cal": ""})
    return blocks


def unroman(s):
    vals = {"I": 1, "V": 5, "X": 10}
    total = 0
    for i, c in enumerate(s):
        v = vals.get(c, 0)
        nxt = vals.get(s[i + 1], 0) if i + 1 < len(s) else 0
        total += -v if v < nxt else v
    return total


def roman(n):
    vals = [(10, "X"), (9, "IX"), (5, "V"), (4, "IV"), (1, "I")]
    out = ""
    for v, s in vals:
        while n >= v:
            out += s
            n -= v
    return out


def previous_plan(html):
    """Parse the PLAN currently in the file so we can preserve started blocks."""
    m = re.search(r"blocks:\s*(\[.*?\])\s*\n\s*\};", html, re.S)
    if not m:
        return []
    raw = m.group(1)
    # Quote keys only where one can legally start — right after { or , — so the
    # colons inside timestamps ("...T20:00:00-04:00") are left alone.
    raw = re.sub(r'([{,]\s*)([A-Za-z_]\w*)\s*:', r'\1"\2":', raw)
    raw = re.sub(r",(\s*[\]}])", r"\1", raw)         # trailing commas
    try:
        return json.loads(raw)
    except Exception:
        return []


def build_plan(now):
    day_start = now.replace(hour=0, minute=0, second=0, microsecond=0)
    day_end = day_start + timedelta(days=1)

    events = []
    for c in CALS:
        url = os.environ.get(c["env"], "").strip()
        if not url:
            die(f"missing secret {c['env']}")
        events += fetch_events(c["env"], url, day_start, day_end, c["label"])

    # Keep anything from the previous plan that has already started — the past is
    # a record, and the block you're in must not be rewritten under you.
    try:
        with open(STILL, encoding="utf-8") as fh:
            prev = previous_plan(fh.read())
    except FileNotFoundError:
        prev = []
    started = [b for b in prev
               if datetime.fromisoformat(b["s"]) <= now
               and datetime.fromisoformat(b["s"]).date() == now.date()]

    # Continue "Quiet time N" numbering past whatever today already used.
    used = 0
    for b in started:
        mt = re.match(r"Quiet time ([IVX]+)$", b.get("t", ""))
        if mt:
            used = max(used, unroman(mt.group(1)))

    fixed = merge_fixed(events)
    blocks = [{"s": iso(f["start"]), "e": iso(f["end"]), "t": f["summary"],
               "type": "fixed", "cal": f["label"]} for f in fixed]
    blocks += fill_gaps(fixed, now, day_start, start_n=used)
    future = [b for b in blocks if datetime.fromisoformat(b["s"]) > now]

    seen, merged = set(), []
    for b in started + future:
        k = (b["s"], b["t"])
        if k in seen:
            continue
        seen.add(k)
        merged.append(b)
    merged.sort(key=lambda b: b["s"])

    # Number the generated blocks only after the future-filter has run, so a
    # dropped candidate never burns a numeral and leaves a gap in the sequence.
    n = used
    for b in merged:
        mt = re.match(r"Quiet time(?: ([IVX]+))?$", b.get("t", "")) if b["type"] == "focus" else None
        if not mt:
            continue
        if datetime.fromisoformat(b["s"]) > now:
            n += 1
            b["t"] = f"Quiet time {roman(n)}"
        elif mt.group(1):
            n = max(n, unroman(mt.group(1)))
    return merged


def render(blocks, now):
    label = now.strftime("%a %b %-d") + " · synced from Joint Plans + Junyan"
    lines = [MARK_START, "const PLAN = {",
             f'  generated: "{iso(now)}",',
             f'  label: "{label}",', "  blocks: ["]
    for i, b in enumerate(blocks):
        tail = "," if i < len(blocks) - 1 else ""
        t = b["t"].replace("\\", "\\\\").replace('"', '\\"')
        cal = b.get("cal", "")
        lines.append(f'    {{ s:"{b["s"]}", e:"{b["e"]}", t:"{t}", '
                     f'type:"{b["type"]}", cal:"{cal}" }}{tail}')
    lines += ["  ]", "};", MARK_END]
    return "\n".join(lines)


def main():
    now = datetime.now(TZ)
    blocks = build_plan(now)
    if not blocks:
        print("No blocks for today — writing nothing.")
        return

    with open(STILL, encoding="utf-8") as fh:
        html = fh.read()

    if MARK_START not in html or MARK_END not in html:
        die("STILL:PLAN markers not found in still/index.html")

    head, rest = html.split(MARK_START, 1)
    _, tail = rest.split(MARK_END, 1)
    new = head + render(blocks, now) + tail

    # Cache-buster so phones never serve a stale plan.
    new = re.sub(r'<meta name="still-version" content="[^"]*">',
                 f'<meta name="still-version" content="{iso(now)}">', new)

    if new == html:
        print("Plan unchanged.")
        return
    with open(STILL, "w", encoding="utf-8") as fh:
        fh.write(new)
    print(f"Wrote {len(blocks)} blocks for {now:%Y-%m-%d %H:%M %Z}.")


if __name__ == "__main__":
    main()
